# -*- coding: utf-8 -*-
"""
/***************************************************************************
 swap_attribute
                                 A QGIS plugin
 this plugin helps to swap the attributes for selected features
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-08
        copyright            : (C) 2025 by vishnudurga
        email                : post2vd@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load swap_attribute class from file swap_attribute.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .swap_attribute import SwapAttribute
    return SwapAttribute(iface)
